import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
  },
  titleContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#3E2723',
    textShadowColor: 'rgba(255, 255, 255, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#4E6E5D',
    fontWeight: '600',
    marginTop: 2,
  },
  tabFilter: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 10,
    marginVertical: 10,
  },
  filterBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#D7CCC8',
  },
  filterBtnActive: {
    backgroundColor: '#2E7D32',
    borderColor: '#1B5E20',
  },
  filterBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#5D4037',
  },
  filterBtnTextActive: {
    color: '#FFF',
  },
  scrollContent: {
    paddingHorizontal: 16,
  },
  missionCard: {
    backgroundColor: '#FAF9F4',
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: '#E0D8C3',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  missionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  missionIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#E8F5E9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#A5D6A7',
  },
  missionTitleWrapper: {
    flex: 1,
  },
  missionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#2E382E',
  },
  missionDesc: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
  },
  progressBarBg: {
    flex: 1,
    height: 10,
    backgroundColor: '#E0E0E0',
    borderRadius: 5,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#43A047',
    borderRadius: 5,
  },
  progressText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#2E7D32',
    minWidth: 32,
    textAlign: 'right',
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#ECE8DD',
  },
  rewardBadges: {
    flexDirection: 'row',
    gap: 6,
  },
  rewardPill: {
    backgroundColor: '#FFF8E1',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFE082',
  },
  rewardPillXP: {
    backgroundColor: '#E8EAF6',
    borderColor: '#C5CAE9',
  },
  rewardPillText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#3E2723',
  },
  claimBtn: {
    backgroundColor: '#2E7D32',
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 14,
    elevation: 2,
  },
  claimBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '800',
  },
  claimedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  claimedText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2E7D32',
  },
  pendingBadge: {
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  pendingText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#888',
  },
});
