import { StyleSheet } from 'react-native';
import {
  alpha,
  palette,
  radius,
  shadows,
  spacing,
} from '../../theme/designSystem';

export default StyleSheet.create({
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xs,
    paddingBottom: 126,
  },
  heroCard: {
    padding: spacing.lg,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: alpha(palette.borderStrong, 0.9),
    backgroundColor: alpha(palette.surface, 0.94),
    ...shadows.md,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: palette.surfaceMuted,
  },
  heroCopy: {
    flex: 1,
  },
  eyebrow: {
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  title: {
    marginTop: spacing.xxs,
    color: palette.textStrong,
    fontSize: 23,
    fontWeight: '900',
    lineHeight: 28,
  },
  subtitle: {
    marginTop: spacing.xs,
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
  },
  progressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  progressLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  progressValue: {
    fontSize: 13,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  progressTrack: {
    width: '100%',
    height: 10,
    overflow: 'hidden',
    borderRadius: radius.pill,
    backgroundColor: palette.disabledSurface,
  },
  progressFill: {
    height: '100%',
    borderRadius: radius.pill,
  },
  filterTitle: {
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
    color: palette.text,
    fontSize: 15,
    fontWeight: '900',
  },
  filterRow: {
    gap: spacing.sm,
    paddingRight: spacing.md,
    paddingBottom: spacing.xs,
  },
  filterChip: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.9),
  },
  filterChipText: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  filterChipTextActive: {
    color: palette.inverseText,
  },
  biomeRow: {
    gap: spacing.sm,
    paddingTop: spacing.sm,
    paddingRight: spacing.md,
    paddingBottom: spacing.sm,
  },
  biomeChip: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.9),
  },
  biomeChipActive: {
    borderColor: palette.primary,
    backgroundColor: palette.primary,
  },
  biomeChipEmoji: {
    minWidth: 20,
    color: palette.text,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  biomeChipText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: '800',
  },
  biomeChipTextActive: {
    color: palette.inverseText,
  },
  biomeSection: {
    marginTop: spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  sectionIcon: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
    borderRadius: radius.md,
  },
  sectionEmoji: {
    fontSize: 24,
  },
  sectionCopy: {
    flex: 1,
  },
  sectionTitle: {
    color: palette.textStrong,
    fontSize: 17,
    fontWeight: '900',
  },
  sectionSubtitle: {
    marginTop: spacing.xxs,
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  sectionCount: {
    minWidth: 48,
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radius.pill,
  },
  sectionCountText: {
    fontSize: 11,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  itemCard: {
    minHeight: 174,
    padding: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    ...shadows.sm,
  },
  itemCardLocked: {
    borderColor: palette.divider,
    backgroundColor: alpha(palette.surfaceMuted, 0.94),
  },
  itemCardPressed: {
    opacity: 0.74,
    transform: [{ scale: 0.98 }],
  },
  artFrame: {
    width: '100%',
    aspectRatio: 1.42,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: radius.md,
  },
  itemEmoji: {
    fontSize: 43,
  },
  itemEmojiLocked: {
    opacity: 0.24,
  },
  lockBadge: {
    position: 'absolute',
    right: 7,
    bottom: 7,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    backgroundColor: palette.textMuted,
  },
  discoveredBadge: {
    position: 'absolute',
    right: 7,
    bottom: 7,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    borderWidth: 2,
    borderColor: palette.surface,
  },
  itemName: {
    minHeight: 34,
    marginTop: spacing.sm,
    color: palette.text,
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 16,
  },
  itemFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  itemCategory: {
    flex: 1,
    fontSize: 10,
    fontWeight: '800',
  },
  emptyCard: {
    alignItems: 'center',
    marginTop: spacing.xl,
    padding: spacing.xl,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.9),
  },
  emptyTitle: {
    marginTop: spacing.md,
    color: palette.text,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyText: {
    maxWidth: 320,
    marginTop: spacing.xs,
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  modalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
    backgroundColor: alpha(palette.black, 0.58),
  },
  modalDismiss: {
    ...StyleSheet.absoluteFillObject,
  },
  modalCard: {
    width: '100%',
    maxWidth: 430,
    maxHeight: '84%',
    overflow: 'hidden',
    borderRadius: radius.xxl,
    borderWidth: 2,
    backgroundColor: palette.surface,
    ...shadows.lg,
  },
  modalHeader: {
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
  },
  modalBiomeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radius.pill,
  },
  modalBiomeEmoji: {
    fontSize: 17,
  },
  modalBiomeText: {
    fontSize: 11,
    fontWeight: '900',
  },
  closeButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceMuted,
  },
  modalContent: {
    padding: spacing.lg,
    paddingTop: spacing.md,
  },
  modalArt: {
    width: '100%',
    minHeight: 172,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.xl,
  },
  modalEmoji: {
    fontSize: 82,
  },
  modalLock: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.md,
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    backgroundColor: palette.textMuted,
  },
  modalTitleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  categoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radius.pill,
  },
  categoryBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  stateBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radius.pill,
  },
  stateBadgeUnlocked: {
    backgroundColor: alpha(palette.success, 0.12),
  },
  stateBadgeLocked: {
    backgroundColor: palette.disabledSurface,
  },
  stateBadgeText: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  stateBadgeTextUnlocked: {
    color: palette.success,
  },
  stateBadgeTextLocked: {
    color: palette.textMuted,
  },
  modalTitle: {
    marginTop: spacing.md,
    color: palette.textStrong,
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 29,
  },
  modalDescription: {
    marginTop: spacing.sm,
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  unlockBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    marginTop: spacing.lg,
    padding: spacing.md,
    borderRadius: radius.lg,
  },
  unlockCopy: {
    flex: 1,
  },
  unlockTitle: {
    color: palette.text,
    fontSize: 12,
    fontWeight: '900',
  },
  unlockText: {
    marginTop: spacing.xs,
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
});
