import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  content: { paddingHorizontal: 16, paddingBottom: 32 },
  heading: { paddingVertical: 15 },
  eyebrow: { color: '#6F8075', fontSize: 10, fontWeight: '900', letterSpacing: 1.3 },
  title: { color: '#17382B', fontSize: 27, fontWeight: '900', marginTop: 4 },
  subtitle: { color: '#6D7A72', fontSize: 14, lineHeight: 21, marginTop: 6 },
  timeline: { marginTop: 7 },
  timelineRow: { flexDirection: 'row', alignItems: 'center', position: 'relative', paddingBottom: 16 },
  timelineLine: { position: 'absolute', width: 4, left: 18, top: 38, bottom: -16, borderRadius: 2, backgroundColor: '#D2DDD5' },
  orderBubble: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', zIndex: 2, borderWidth: 3, borderColor: '#FFFFFF' },
  orderText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
  card: { flex: 1, minHeight: 132, marginLeft: 11, borderRadius: 22, backgroundColor: '#FFFFFF', flexDirection: 'row', overflow: 'hidden', borderWidth: 1, borderColor: '#E0E8E2', shadowColor: '#1D382D', shadowOpacity: 0.09, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  cover: { width: 104, alignItems: 'center', justifyContent: 'center' },
  biomeEmoji: { fontSize: 48 },
  levelPill: { backgroundColor: 'rgba(255,255,255,0.18)', borderRadius: 11, paddingHorizontal: 8, paddingVertical: 4, marginTop: 7 },
  levelText: { color: '#FFFFFF', fontSize: 9, fontWeight: '900' },
  cardBody: { flex: 1, padding: 13 },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center' },
  biomeName: { flex: 1, color: '#203B30', fontSize: 16, fontWeight: '900' },
  activePill: { borderRadius: 9, paddingHorizontal: 7, paddingVertical: 4 },
  activeText: { fontSize: 8, fontWeight: '900', letterSpacing: 0.5 },
  description: { color: '#738078', fontSize: 11, lineHeight: 16, marginTop: 6 },
  progressRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 'auto' },
  progressText: { color: '#53645B', fontSize: 10, fontWeight: '800' },
  footerSpace: { height: 20 },
});
