import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  missing: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 9, gap: 8 },
  closeButton: { width: 38, height: 38, borderRadius: 14, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E0E7E2' },
  progressTrack: { flex: 1, height: 10, borderRadius: 8, backgroundColor: '#DDE5DF', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 8 },
  headerStat: { backgroundColor: '#FFFFFF', borderRadius: 12, paddingHorizontal: 7, paddingVertical: 8, color: '#34473D', fontSize: 11, fontWeight: '900' },
  body: { flex: 1, paddingHorizontal: 16, paddingBottom: 16 },
  level: { fontSize: 10, letterSpacing: 1.1, fontWeight: '900', marginTop: 8 },
  title: { color: '#18362B', fontSize: 25, fontWeight: '900', marginTop: 4 },
  subtitle: { color: '#728078', fontSize: 13, marginTop: 4, marginBottom: 14 },
  storyWrap: { flex: 1 },
  storyScene: { minHeight: 235, borderRadius: 27, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  sceneOrb: { position: 'absolute', width: 250, height: 250, borderRadius: 125, backgroundColor: 'rgba(255,255,255,0.08)', top: -110, right: -60 },
  sceneEmoji: { fontSize: 86 },
  sceneTag: { position: 'absolute', left: 14, top: 14, backgroundColor: 'rgba(0,0,0,0.22)', borderRadius: 13, paddingHorizontal: 10, paddingVertical: 7, flexDirection: 'row', alignItems: 'center', gap: 6 },
  sceneTagText: { color: '#FFFFFF', fontSize: 10, fontWeight: '900', letterSpacing: 0.8 },
  storyCard: { backgroundColor: '#FFFFFF', borderRadius: 22, padding: 19, marginTop: -24, marginHorizontal: 10, shadowColor: '#19352A', shadowOpacity: 0.13, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 5 },
  storyText: { color: '#294038', fontSize: 16, lineHeight: 25, fontWeight: '600' },
  pageText: { color: '#8B9690', fontSize: 10, fontWeight: '800', marginTop: 14 },
  actionButton: { minHeight: 54, borderRadius: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 16, paddingHorizontal: 20 },
  actionButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '900' },
  questionContent: { paddingBottom: 20 },
  questionCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 20, padding: 16, borderWidth: 1, borderColor: '#E3E9E5' },
  questionIcon: { width: 45, height: 45, borderRadius: 15, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  questionText: { flex: 1, color: '#213C31', fontSize: 16, lineHeight: 23, fontWeight: '800' },
  optionsWrap: { marginTop: 14, gap: 9 },
  option: { minHeight: 60, borderRadius: 17, borderWidth: 2, borderColor: '#DFE6E1', backgroundColor: '#FFFFFF', padding: 11, flexDirection: 'row', alignItems: 'center' },
  optionCorrect: { borderColor: '#3DA75A', backgroundColor: '#EAF8EE' },
  optionWrong: { borderColor: '#D95656', backgroundColor: '#FDEEEE' },
  optionLetter: { width: 34, color: '#607067', fontWeight: '900', textAlign: 'center' },
  optionText: { flex: 1, color: '#30463C', fontSize: 14, fontWeight: '700' },
  feedback: { marginTop: 13, borderRadius: 17, padding: 14, borderWidth: 1 },
  feedbackGood: { backgroundColor: '#EAF8EE', borderColor: '#BDE4C6' },
  feedbackBad: { backgroundColor: '#FFF3E8', borderColor: '#F0D0B2' },
  feedbackTitle: { color: '#284538', fontWeight: '900', fontSize: 13 },
  feedbackText: { color: '#5C6B63', fontSize: 12, lineHeight: 18, marginTop: 3 },
  resultWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 22 },
  resultHalo: { width: 126, height: 126, borderRadius: 63, alignItems: 'center', justifyContent: 'center' },
  resultEmoji: { fontSize: 66 },
  resultEyebrow: { color: '#718078', fontSize: 10, fontWeight: '900', letterSpacing: 1.3, marginTop: 17 },
  resultTitle: { color: '#18372B', fontSize: 27, fontWeight: '900', marginTop: 5 },
  resultSubtitle: { color: '#68766E', fontSize: 14, textAlign: 'center', marginTop: 6 },
  rewardRow: { width: '100%', flexDirection: 'row', gap: 8, marginTop: 22 },
  rewardCard: { flex: 1, backgroundColor: '#FFFFFF', borderRadius: 17, alignItems: 'center', paddingVertical: 14, borderWidth: 1, borderColor: '#E0E7E2' },
  rewardValue: { color: '#233E33', fontSize: 17, fontWeight: '900', marginTop: 4 },
  rewardLabel: { color: '#87928B', fontSize: 10 },
});
