import { StyleSheet } from 'react-native';

import {
  alpha,
  palette,
  radius,
  shadows,
  spacing,
} from '../../theme/designSystem';

export default StyleSheet.create({
  header: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  headerButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.9),
    ...shadows.sm,
  },
  headerButtonPlaceholder: {
    width: 42,
    height: 42,
  },
  headerCopy: {
    flex: 1,
    alignItems: 'center',
  },
  headerEyebrow: {
    color: palette.textMuted,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  headerTitle: {
    marginTop: 2,
    color: palette.textStrong,
    fontSize: 20,
    fontWeight: '900',
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: 126,
  },
  profileCard: {
    marginTop: spacing.xs,
    alignItems: 'center',
    padding: 20,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: alpha(palette.borderStrong, 0.9),
    backgroundColor: alpha(palette.surface, 0.95),
    ...shadows.md,
  },
  avatarWrap: {
    position: 'relative',
  },
  avatar: {
    width: 84,
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 29,
    borderWidth: 3,
    borderColor: palette.primary,
    backgroundColor: palette.primarySoft,
  },
  levelBadge: {
    position: 'absolute',
    right: -7,
    bottom: -7,
    minWidth: 31,
    height: 31,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderRadius: 16,
    borderWidth: 3,
    borderColor: palette.white,
    backgroundColor: palette.warning,
    ...shadows.sm,
  },
  levelBadgeText: {
    color: '#593500',
    fontSize: 12,
    fontWeight: '900',
  },
  userName: {
    marginTop: 15,
    color: palette.textStrong,
    fontSize: 21,
    fontWeight: '900',
    textAlign: 'center',
  },
  userEmail: {
    marginTop: 3,
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  rolePill: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: radius.pill,
    backgroundColor: alpha(palette.warning, 0.13),
  },
  roleText: {
    color: '#8D5C00',
    fontSize: 11,
    fontWeight: '900',
  },
  xpBlock: {
    width: '100%',
    marginTop: 18,
  },
  xpLabels: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 7,
  },
  xpLabel: {
    color: palette.primaryDeep,
    fontSize: 12,
    fontWeight: '900',
  },
  xpValue: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  progressTrack: {
    height: 11,
    overflow: 'hidden',
    borderRadius: radius.pill,
    backgroundColor: palette.disabledSurface,
  },
  xpFill: {
    height: '100%',
    borderRadius: radius.pill,
    backgroundColor: palette.primary,
  },
  nextLevel: {
    marginTop: 5,
    color: palette.textSubtle,
    fontSize: 9,
    fontWeight: '700',
    textAlign: 'right',
  },
  walletRow: {
    width: '100%',
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 11,
    borderRadius: radius.lg,
    backgroundColor: palette.surfaceMuted,
  },
  walletItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  walletDivider: {
    width: 1,
    height: 32,
    backgroundColor: palette.border,
  },
  walletValue: {
    marginTop: 2,
    color: palette.textStrong,
    fontSize: 15,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  walletLabel: {
    marginTop: 1,
    color: palette.textMuted,
    fontSize: 9,
    fontWeight: '700',
  },
  sectionHeading: {
    marginTop: 25,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  sectionEyebrow: {
    color: palette.textSubtle,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  sectionTitle: {
    marginTop: 3,
    color: palette.textStrong,
    fontSize: 18,
    fontWeight: '900',
  },
  percentPill: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: radius.pill,
    backgroundColor: palette.primarySoft,
  },
  percentPillText: {
    color: palette.primaryDark,
    fontSize: 12,
    fontWeight: '900',
  },
  biomeList: {
    gap: 8,
  },
  biomeCard: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    padding: 11,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.93),
  },
  biomeCardLocked: {
    opacity: 0.62,
    backgroundColor: alpha(palette.disabledSurface, 0.86),
  },
  biomeIcon: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
  },
  biomeEmoji: {
    fontSize: 23,
  },
  biomeCopy: {
    flex: 1,
    minWidth: 0,
  },
  biomeTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  biomeName: {
    flex: 1,
    color: palette.text,
    fontSize: 13,
    fontWeight: '900',
  },
  biomePercent: {
    fontSize: 11,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  biomeMetaRow: {
    marginTop: 3,
    flexDirection: 'row',
    gap: 12,
  },
  biomeMeta: {
    color: palette.textMuted,
    fontSize: 9,
    fontWeight: '700',
  },
  biomeProgressTrack: {
    height: 6,
    marginTop: 7,
    overflow: 'hidden',
    borderRadius: radius.pill,
    backgroundColor: palette.disabledSurface,
  },
  biomeProgressFill: {
    height: '100%',
    borderRadius: radius.pill,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statCard: {
    width: '31.5%',
    minWidth: 90,
    flexGrow: 1,
    minHeight: 90,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 9,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.93),
  },
  statValue: {
    marginTop: 5,
    color: palette.textStrong,
    fontSize: 17,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  statLabel: {
    marginTop: 2,
    color: palette.textMuted,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  achievementCount: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: radius.pill,
    backgroundColor: alpha(palette.warning, 0.14),
  },
  achievementCountText: {
    color: '#8D5C00',
    fontSize: 11,
    fontWeight: '900',
  },
  achievementList: {
    gap: 8,
  },
  achievementCard: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    padding: 11,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surfaceMuted, 0.9),
  },
  achievementCardComplete: {
    borderColor: alpha(palette.primary, 0.34),
    backgroundColor: alpha(palette.primarySoft, 0.57),
  },
  achievementIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: palette.disabledSurface,
  },
  achievementIconComplete: {
    backgroundColor: palette.primary,
  },
  achievementCopy: {
    flex: 1,
  },
  achievementTitle: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '900',
  },
  achievementDescription: {
    marginTop: 2,
    color: palette.textMuted,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '600',
  },
  accountCard: {
    marginTop: 25,
    padding: 14,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.93),
    ...shadows.sm,
  },
  accountHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 3,
    paddingBottom: 11,
  },
  accountTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: '900',
  },
  resetButton: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: radius.lg,
    backgroundColor: '#FFF5E8',
  },
  logoutButton: {
    minHeight: 58,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: radius.lg,
    backgroundColor: '#FFF0F0',
  },
  actionCopy: {
    flex: 1,
  },
  resetButtonText: {
    color: '#9B5200',
    fontSize: 12,
    fontWeight: '900',
  },
  logoutButtonText: {
    color: '#C53B3B',
    fontSize: 12,
    fontWeight: '900',
  },
  actionHint: {
    marginTop: 2,
    color: palette.textMuted,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '600',
  },
  version: {
    marginTop: 18,
    color: palette.textSubtle,
    fontSize: 9,
    fontWeight: '700',
    textAlign: 'center',
  },
  pressed: {
    opacity: 0.72,
    transform: [{ scale: 0.98 }],
  },
});
