import { StyleSheet } from 'react-native';
import {
  alpha,
  palette,
  radius,
  shadows,
  spacing,
} from '../../theme/designSystem';

export default StyleSheet.create({
  content: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxl,
  },
  headingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  headingCopy: {
    flex: 1,
    minWidth: 0,
  },
  eyebrow: {
    color: palette.primaryDark,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.15,
  },
  title: {
    marginTop: spacing.xs,
    color: palette.textStrong,
    fontSize: 25,
    fontWeight: '900',
    lineHeight: 30,
  },
  subtitle: {
    marginTop: spacing.xs,
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
  },
  storeIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    backgroundColor: alpha(palette.surface, 0.92),
    ...shadows.sm,
  },
  walletRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  walletCard: {
    flex: 1,
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.96),
    ...shadows.sm,
  },
  walletIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
  },
  walletLabel: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  walletValue: {
    color: palette.textStrong,
    fontSize: 19,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  inventorySummary: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: alpha(palette.primary, 0.28),
    backgroundColor: alpha(palette.primarySoft, 0.7),
  },
  inventoryIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: alpha(palette.surface, 0.88),
  },
  inventoryCopy: {
    flex: 1,
  },
  inventoryTitle: {
    color: palette.textStrong,
    fontSize: 13,
    fontWeight: '900',
  },
  inventorySubtitle: {
    marginTop: spacing.xxs,
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  inventoryCount: {
    minWidth: 31,
    color: palette.primaryDark,
    fontSize: 21,
    fontWeight: '900',
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  activeBoosts: {
    marginBottom: spacing.md,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: alpha(palette.secondary, 0.32),
    backgroundColor: alpha(palette.secondarySoft, 0.78),
  },
  sectionLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  sectionLabel: {
    color: palette.secondaryDark,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  boostList: {
    gap: spacing.xs,
  },
  boostChip: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: alpha(palette.surface, 0.84),
  },
  boostName: {
    flex: 1,
    color: palette.text,
    fontSize: 12,
    fontWeight: '800',
  },
  boostTime: {
    color: palette.secondaryDark,
    fontSize: 11,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  feedback: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
  },
  feedbackSuccess: {
    borderColor: alpha(palette.success, 0.35),
    backgroundColor: alpha(palette.success, 0.1),
  },
  feedbackWarning: {
    borderColor: alpha(palette.warning, 0.4),
    backgroundColor: alpha(palette.warning, 0.1),
  },
  feedbackText: {
    flex: 1,
    color: palette.text,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  tabs: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginBottom: spacing.md,
    padding: spacing.xs,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.78),
  },
  tab: {
    flex: 1,
    minHeight: 45,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
    borderRadius: radius.md,
  },
  tabActive: {
    backgroundColor: palette.primaryDark,
    ...shadows.sm,
  },
  tabPressed: {
    opacity: 0.76,
    transform: [{ scale: 0.98 }],
  },
  tabText: {
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: '800',
  },
  tabTextActive: {
    color: palette.inverseText,
  },
  tabCount: {
    minWidth: 19,
    height: 19,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: palette.surfaceMuted,
  },
  tabCountActive: {
    backgroundColor: alpha(palette.white, 0.2),
  },
  tabCountText: {
    color: palette.textMuted,
    fontSize: 9,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  tabCountTextActive: {
    color: palette.inverseText,
  },
  itemsGrid: {
    gap: spacing.md,
  },
  itemCard: {
    padding: spacing.md,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.96),
    ...shadows.sm,
  },
  itemTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  itemIconBox: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceMuted,
  },
  itemIcon: {
    fontSize: 29,
  },
  quantityBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    minWidth: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    borderRadius: radius.pill,
    borderWidth: 2,
    borderColor: palette.surface,
    backgroundColor: palette.primaryDark,
  },
  quantityText: {
    color: palette.inverseText,
    fontSize: 9,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  itemCopy: {
    flex: 1,
    minWidth: 0,
  },
  itemName: {
    color: palette.textStrong,
    fontSize: 15,
    fontWeight: '900',
  },
  itemDescription: {
    marginTop: spacing.xs,
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
  },
  effectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radius.sm,
    backgroundColor: alpha(palette.primarySoft, 0.62),
  },
  effectText: {
    flex: 1,
    color: palette.primaryDeep,
    fontSize: 11,
    fontWeight: '800',
  },
  itemFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginTop: spacing.md,
  },
  pricePill: {
    minHeight: 37,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceMuted,
  },
  priceText: {
    color: palette.textStrong,
    fontSize: 14,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  buyButton: {
    minWidth: 108,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    borderRadius: radius.pill,
    borderBottomWidth: 3,
    borderBottomColor: palette.primaryDeep,
    backgroundColor: palette.primary,
  },
  buyButtonUnavailable: {
    borderBottomColor: palette.disabled,
    backgroundColor: palette.disabledSurface,
  },
  buyButtonPressed: {
    opacity: 0.78,
    transform: [{ translateY: 1 }],
    borderBottomWidth: 2,
  },
  buyButtonText: {
    color: palette.inverseText,
    fontSize: 12,
    fontWeight: '900',
  },
  emptyState: {
    alignItems: 'center',
    marginTop: spacing.sm,
    padding: spacing.xxl,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: palette.borderStrong,
    backgroundColor: alpha(palette.surface, 0.68),
  },
  emptyTitle: {
    marginTop: spacing.sm,
    color: palette.text,
    fontSize: 15,
    fontWeight: '900',
  },
  emptyText: {
    marginTop: spacing.xs,
    color: palette.textMuted,
    fontSize: 12,
    textAlign: 'center',
  },
  shopTip: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    marginTop: spacing.lg,
    padding: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: alpha(palette.warning, 0.1),
  },
  shopTipText: {
    flex: 1,
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
  },
});
