import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  scrollContent: { paddingHorizontal: 16, paddingBottom: 126 },
  chapterCard: { borderRadius: 28, padding: 20, marginTop: 6, shadowColor: '#10271E', shadowOpacity: 0.22, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 8 },
  chapterTopRow: { flexDirection: 'row', alignItems: 'flex-start' },
  chapterCopy: { flex: 1, paddingRight: 12 },
  eyebrow: { color: 'rgba(255,255,255,0.72)', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  chapterTitle: { color: '#FFFFFF', fontSize: 24, fontWeight: '900', marginTop: 5 },
  chapterDescription: { color: 'rgba(255,255,255,0.78)', fontSize: 13, lineHeight: 19, marginTop: 6 },
  mapButton: { width: 42, height: 42, borderRadius: 15, backgroundColor: 'rgba(255,255,255,0.14)', alignItems: 'center', justifyContent: 'center' },
  progressMeta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 18, marginBottom: 7 },
  progressLabel: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  progressTrack: { height: 9, borderRadius: 8, backgroundColor: 'rgba(0,0,0,0.18)', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 8 },
  modeRow: { flexDirection: 'row', marginTop: 16, gap: 8 },
  modeActive: { flex: 1, height: 42, borderRadius: 14, backgroundColor: '#FFFFFF', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  modeActiveText: { fontWeight: '900', fontSize: 12 },
  modeButton: { flex: 1.35, height: 42, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.13)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  modeButtonText: { color: '#FFFFFF', fontWeight: '800', fontSize: 12 },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 26, marginBottom: 8 },
  sectionEyebrow: { color: '#738078', fontSize: 10, fontWeight: '900', letterSpacing: 1.1 },
  sectionTitle: { color: '#18372C', fontSize: 18, fontWeight: '900', marginTop: 3 },
  ecoPill: { flexDirection: 'row', gap: 5, alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 20, borderWidth: 1.5, paddingHorizontal: 11, paddingVertical: 7 },
  ecoPillText: { fontSize: 12, fontWeight: '900' },
  pathContainer: { alignItems: 'center', paddingTop: 14 },
  nodeRow: { width: '100%', minHeight: 126, alignItems: 'center', position: 'relative' },
  pathLine: { position: 'absolute', width: 8, height: 55, top: -48, left: '50%', marginLeft: -4, borderRadius: 4, backgroundColor: '#D5DDD7' },
  lessonNode: { width: 76, height: 70, borderRadius: 24, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderBottomWidth: 7, shadowColor: '#233B31', shadowOpacity: 0.14, shadowRadius: 7, shadowOffset: { width: 0, height: 5 }, elevation: 5 },
  lessonNodeLocked: { backgroundColor: '#E6EAE7', borderColor: '#CDD4CF' },
  pressed: { transform: [{ translateY: 3 }], borderBottomWidth: 4 },
  levelBadge: { position: 'absolute', right: -9, top: -9, minWidth: 25, height: 25, paddingHorizontal: 5, borderRadius: 13, backgroundColor: '#EBF0EC', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#FFFFFF' },
  levelBadgeText: { color: '#66736B', fontSize: 10, fontWeight: '900' },
  nodeLabel: { marginTop: 8, backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 6, alignItems: 'center', maxWidth: 184 },
  nodeTitle: { color: '#203C31', fontSize: 12, fontWeight: '900' },
  nodeSubtitle: { color: '#78827C', fontSize: 10, marginTop: 1 },
  finalCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 22, padding: 15, borderWidth: 2, marginTop: 4 },
  finalIcon: { width: 52, height: 52, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  finalCopy: { flex: 1, marginLeft: 12 },
  finalEyebrow: { color: '#819087', fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  finalTitle: { color: '#1A382D', fontSize: 14, fontWeight: '900', marginTop: 2 },
  finalDescription: { color: '#68756E', fontSize: 11, marginTop: 3 },
  transitionButton: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginLeft: 8 },
});
