import { StyleSheet } from 'react-native';

import {
  alpha,
  palette,
  radius,
  shadows,
  spacing,
} from '../../theme/designSystem';

export default StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.xxl,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: spacing.sm,
  },
  brandMark: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary,
    borderBottomWidth: 4,
    borderBottomColor: palette.primaryDark,
    ...shadows.sm,
  },
  brandName: {
    color: palette.textStrong,
    fontSize: 21,
    lineHeight: 23,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  brandTag: {
    marginTop: 2,
    color: palette.textMuted,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 1,
  },
  hero: {
    alignItems: 'center',
    paddingTop: 34,
  },
  eyebrowPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: alpha(palette.primary, 0.3),
    backgroundColor: alpha(palette.primary, 0.1),
  },
  eyebrowText: {
    color: palette.primaryDark,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  title: {
    marginTop: 18,
    color: palette.textStrong,
    fontSize: 34,
    lineHeight: 39,
    fontWeight: '900',
    letterSpacing: -1.2,
    textAlign: 'center',
  },
  titleAccent: {
    color: palette.primaryDark,
    fontSize: 34,
    lineHeight: 39,
    fontWeight: '900',
    letterSpacing: -1.2,
    textAlign: 'center',
  },
  subtitle: {
    maxWidth: 560,
    marginTop: 14,
    color: palette.textMuted,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
    textAlign: 'center',
  },
  pathCard: {
    width: '100%',
    maxWidth: 480,
    marginTop: 26,
    paddingHorizontal: 30,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: alpha(palette.borderStrong, 0.85),
    backgroundColor: alpha(palette.surface, 0.92),
    ...shadows.md,
  },
  pathLine: {
    position: 'absolute',
    left: '20%',
    right: '20%',
    top: 43,
    height: 5,
    borderRadius: radius.pill,
    backgroundColor: palette.border,
  },
  pathStep: {
    width: 72,
    alignItems: 'center',
    zIndex: 1,
  },
  pathNode: {
    width: 54,
    height: 54,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: palette.white,
    ...shadows.sm,
  },
  pathLabel: {
    marginTop: 7,
    color: palette.text,
    fontSize: 11,
    fontWeight: '900',
  },
  featureRow: {
    width: '100%',
    maxWidth: 480,
    marginTop: 14,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  featureItem: {
    flex: 1,
    minHeight: 78,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    paddingVertical: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: alpha(palette.surface, 0.78),
  },
  featureValue: {
    marginTop: 2,
    color: palette.textStrong,
    fontSize: 18,
    fontWeight: '900',
  },
  featureLabel: {
    marginTop: 1,
    color: palette.textMuted,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  actions: {
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
    marginTop: 24,
  },
  primaryButton: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    borderRadius: radius.xl,
    borderBottomWidth: 5,
    borderBottomColor: palette.primaryDark,
    backgroundColor: palette.primary,
    ...shadows.md,
  },
  primaryIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: alpha(palette.white, 0.92),
  },
  buttonCopy: {
    flex: 1,
    paddingHorizontal: spacing.md,
  },
  primaryButtonText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
  },
  primaryButtonHint: {
    marginTop: 2,
    color: alpha(palette.white, 0.78),
    fontSize: 10,
    fontWeight: '700',
  },
  accountRow: {
    marginTop: spacing.md,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: alpha(palette.primaryDark, 0.28),
    backgroundColor: palette.surface,
  },
  outlineButton: {
    flex: 1,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: alpha(palette.secondary, 0.3),
    backgroundColor: alpha(palette.secondarySoft, 0.72),
  },
  secondaryButtonText: {
    color: palette.primaryDeep,
    fontSize: 13,
    fontWeight: '900',
  },
  outlineButtonText: {
    color: palette.secondaryDark,
    fontSize: 13,
    fontWeight: '900',
  },
  buttonPressed: {
    opacity: 0.84,
    transform: [{ translateY: 2 }],
  },
  footerText: {
    marginTop: spacing.lg,
    paddingHorizontal: spacing.lg,
    color: palette.textSubtle,
    fontSize: 10,
    lineHeight: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
});
