import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  content: { paddingHorizontal: 16, paddingBottom: 128 },
  hero: { borderRadius: 26, padding: 19 },
  eyebrow: { color: 'rgba(255,255,255,0.68)', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  title: { color: '#FFFFFF', fontSize: 24, fontWeight: '900', marginTop: 4 },
  subtitle: { color: 'rgba(255,255,255,0.75)', fontSize: 12, marginTop: 4 },
  statRow: { flexDirection: 'row', gap: 8, marginTop: 16 },
  stat: { flex: 1, backgroundColor: 'rgba(255,255,255,0.12)', borderRadius: 14, paddingVertical: 10, alignItems: 'center' },
  statValue: { color: '#FFFFFF', fontSize: 15, fontWeight: '900' },
  statLabel: { color: 'rgba(255,255,255,0.68)', fontSize: 9, marginTop: 2 },
  tapCore: { width: 174, height: 174, borderRadius: 87, alignSelf: 'center', marginVertical: 25, borderWidth: 3, padding: 9, backgroundColor: '#FFFFFF', shadowColor: '#173A2B', shadowOpacity: 0.2, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 7 },
  tapInner: { flex: 1, borderRadius: 76, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 7, borderBottomColor: 'rgba(0,0,0,0.18)' },
  tapEmoji: { fontSize: 42 },
  tapTitle: { color: '#FFFFFF', fontSize: 12, fontWeight: '900', letterSpacing: 0.7, marginTop: 3 },
  tapPower: { color: 'rgba(255,255,255,0.78)', fontSize: 10, marginTop: 2 },
  tapGain: { position: 'absolute', top: -16, right: 2, fontSize: 22, fontWeight: '900' },
  treeHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  treeEyebrow: { color: '#77847C', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  treeTitle: { color: '#18372C', fontSize: 19, fontWeight: '900', marginTop: 2 },
  trackButton: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#FFFFFF', paddingHorizontal: 11, paddingVertical: 8, borderRadius: 13 },
  trackButtonText: { fontSize: 11, fontWeight: '900' },
  branches: { gap: 10, paddingBottom: 8 },
  branch: { width: 136, backgroundColor: 'rgba(255,255,255,0.62)', borderRadius: 20, padding: 10, alignItems: 'center' },
  branchHeader: { width: '100%', minHeight: 35, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4 },
  branchTitle: { color: '#FFFFFF', fontSize: 8, fontWeight: '900', letterSpacing: 0.6 },
  nodeSlot: { paddingTop: 18, alignItems: 'center' },
  connector: { position: 'absolute', width: 5, height: 21, top: -2, backgroundColor: '#CDD5D0' },
  treeNode: { width: 106, minHeight: 100, borderRadius: 22, borderWidth: 3, borderBottomWidth: 6, borderColor: '#CDD5D0', backgroundColor: '#EEF1EF', alignItems: 'center', justifyContent: 'center', padding: 7 },
  nodeEmoji: { fontSize: 27 },
  nodeName: { color: '#34483E', fontSize: 10, fontWeight: '900', textAlign: 'center', marginTop: 3 },
  nodeCost: { color: '#738077', fontSize: 9, fontWeight: '800', marginTop: 3 },
  nodeNameUnlocked: { color: '#FFFFFF' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(16,30,23,0.55)', alignItems: 'center', justifyContent: 'center', padding: 22 },
  modalCard: { width: '100%', maxWidth: 430, backgroundColor: '#FFFFFF', borderRadius: 27, padding: 22, alignItems: 'center' },
  modalClose: { position: 'absolute', right: 14, top: 14, width: 34, height: 34, borderRadius: 17, backgroundColor: '#EFF3F0', alignItems: 'center', justifyContent: 'center' },
  modalEmoji: { fontSize: 58, marginTop: 5 },
  modalTitle: { color: '#18372C', fontSize: 23, fontWeight: '900', marginTop: 8 },
  modalDescription: { color: '#67766D', fontSize: 13, lineHeight: 20, textAlign: 'center', marginTop: 7 },
  requirements: { width: '100%', flexDirection: 'row', gap: 6, marginTop: 18 },
  requirement: { flex: 1, backgroundColor: '#F1F5F2', borderRadius: 11, paddingVertical: 8, color: '#45594E', fontSize: 10, fontWeight: '800', textAlign: 'center' },
  buyButton: { width: '100%', minHeight: 51, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 16 },
  buyButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },
});
