import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  outerContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingBottom: Platform.OS === 'android' ? 4 : 10,
    paddingHorizontal: 4,
    zIndex: 999,
  },
  navShell: {
    width: width - 8,
    height: 92,
    position: 'relative',
    justifyContent: 'flex-end',
    overflow: 'visible',
  },
  woodBarImage: {
    position: 'absolute',
    left: 0,
    bottom: -6,
    width: '100%',
    height: 184,
  },
  navRow: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 7,
    height: 76,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 6,
  },
  navItem: {
    flex: 1,
    height: 62,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    marginHorizontal: 1,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  navItemActive: {
    backgroundColor: 'rgba(27, 94, 32, 0.36)',
    borderColor: 'rgba(255, 224, 130, 0.7)',
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(52, 28, 12, 0.58)',
    borderWidth: 1.4,
    borderColor: 'rgba(255, 232, 184, 0.55)',
  },
  iconCircleActive: {
    backgroundColor: '#2E7D32',
    borderColor: '#FFE082',
    transform: [{ scale: 1.08 }],
  },
  navText: {
    fontSize: 9.5,
    fontWeight: '900',
    color: '#FFE8B8',
    marginTop: 3,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  navTextActive: {
    color: '#FFF9C4',
    fontWeight: '900',
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#E53935',
    minWidth: 17,
    height: 17,
    borderRadius: 8.5,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: '#FFF',
  },
  badgeText: {
    color: '#FFF',
    fontSize: 9,
    fontWeight: '900',
  },

  // BOTÃO CENTRAL DO MAPA
  centerItemWrapper: {
    flex: 1.2,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -21,
  },
  centerButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerGlobeRing: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#2E7D32',
    borderWidth: 3,
    borderColor: '#FFE082',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.38,
    shadowRadius: 8,
    elevation: 8,
  },
  centerGlobeRingActive: {
    backgroundColor: '#1B5E20',
    borderColor: '#FFF',
    transform: [{ scale: 1.08 }],
    shadowColor: '#4CAF50',
    shadowOpacity: 0.6,
  },
  centerText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#FFE8B8',
    marginTop: 2,
    textShadowColor: 'rgba(0, 0, 0, 0.85)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  centerTextActive: {
    color: '#FFF',
  },
});
