import { StyleSheet } from 'react-native';
import {
  alpha,
  layout,
  palette,
  radius,
  shadows,
  spacing,
} from '../../theme/designSystem';

export default StyleSheet.create({
  outerContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xs,
  },
  navShell: {
    width: '100%',
    maxWidth: layout.maxContentWidth,
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'stretch',
    padding: spacing.xs,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: alpha(palette.borderStrong, 0.92),
    backgroundColor: alpha(palette.surface, 0.97),
    ...shadows.lg,
  },
  navItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 60,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.lg,
    paddingHorizontal: spacing.xxs,
    paddingVertical: spacing.xs,
  },
  navItemActive: {
    backgroundColor: palette.primarySoft,
  },
  navItemPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.97 }],
  },
  iconCircle: {
    width: 34,
    height: 34,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
  },
  iconCircleActive: {
    backgroundColor: palette.primary,
    ...shadows.sm,
  },
  navText: {
    maxWidth: '100%',
    marginTop: spacing.xxs,
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  navTextActive: {
    color: palette.primaryDeep,
    fontWeight: '900',
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -8,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderRadius: radius.pill,
    borderWidth: 1.5,
    borderColor: palette.surface,
    backgroundColor: palette.danger,
  },
  badgeText: {
    color: palette.inverseText,
    fontSize: 9,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
});
