import { StyleSheet } from 'react-native';
import {
  alpha,
  layout,
  palette,
  radius,
  shadows,
  spacing,
} from '../../theme/designSystem';

export default StyleSheet.create({
  outerContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.md,
  },
  navShell: {
    width: '100%',
    maxWidth: layout.maxContentWidth,
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingHorizontal: spacing.xs,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xxs,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderTopWidth: 2,
    borderColor: alpha(palette.borderStrong, 0.95),
    borderTopColor: palette.bark,
    backgroundColor: alpha(palette.surfaceRaised, 0.98),
    ...shadows.md,
  },
  navItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xxs,
    paddingVertical: spacing.xs,
  },
  navItemFeatured: {
    minHeight: 72,
    marginTop: -20,
  },
  navItemActive: {
    backgroundColor: palette.transparent,
  },
  navItemPressed: {
    opacity: 0.68,
  },
  iconFrame: {
    width: 34,
    height: 30,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.sm,
  },
  iconFrameActive: {
    backgroundColor: palette.primarySoft,
  },
  iconFrameFeatured: {
    width: 54,
    height: 54,
    borderRadius: radius.xl,
    borderWidth: 3,
    borderColor: palette.surfaceRaised,
    backgroundColor: palette.moss,
    ...shadows.md,
  },
  iconFrameFeaturedActive: {
    borderColor: palette.sun,
    backgroundColor: palette.primaryDeep,
  },
  navText: {
    maxWidth: '100%',
    marginTop: 3,
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
  },
  navTextFeatured: {
    marginTop: 2,
    color: palette.primaryDeep,
    fontWeight: '800',
  },
  navTextActive: {
    color: palette.primaryDeep,
    fontWeight: '900',
  },
  activeMark: {
    width: 18,
    height: 2,
    marginTop: 3,
    borderRadius: radius.xs,
    backgroundColor: palette.transparent,
  },
  activeMarkVisible: {
    backgroundColor: palette.clay,
  },
  activeMarkFeatured: {
    backgroundColor: palette.sun,
  },
  badge: {
    position: 'absolute',
    top: -5,
    right: -7,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: palette.surfaceRaised,
    backgroundColor: palette.danger,
  },
  badgeText: {
    color: palette.inverseText,
    fontSize: 9,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
});
