import { StyleSheet } from 'react-native';
import { alpha, layout, palette, shadows, spacing } from '../../theme/designSystem';

export default StyleSheet.create({
  content: {
    width: '100%',
    maxWidth: layout.maxContentWidth,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: 128,
  },
  headingRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md, paddingTop: spacing.sm, paddingBottom: spacing.lg },
  headingCopy: { flex: 1 },
  kicker: { color: palette.mossDeep, fontSize: 10, fontWeight: '800', letterSpacing: 1.4 },
  title: { color: palette.textStrong, fontFamily: 'Georgia', fontSize: 29, fontWeight: '700', marginTop: 4 },
  subtitle: { color: palette.textMuted, fontSize: 13, lineHeight: 19, marginTop: 5, maxWidth: 470 },
  weatherTag: { flexDirection: 'row', alignItems: 'center', gap: 5, borderBottomWidth: 1, borderColor: palette.line, paddingBottom: 5, marginTop: 3 },
  weatherText: { color: palette.text, fontSize: 10, fontWeight: '700' },
  diorama: { minHeight: 350, borderWidth: 2, backgroundColor: palette.paperRaised, overflow: 'hidden', ...shadows.md },
  scenePressable: { height: 306, overflow: 'hidden' },
  sky: { position: 'absolute', top: 0, left: 0, right: 0, height: '59%' },
  sun: { position: 'absolute', width: 33, height: 33, borderRadius: 20, right: 30, top: 24, backgroundColor: alpha(palette.sun, 0.8), borderWidth: 6, borderColor: alpha(palette.paperRaised, 0.5) },
  contour: { position: 'absolute', borderWidth: 1, borderRadius: 999, transform: [{ rotate: '-8deg' }] },
  contourOne: { width: 220, height: 84, left: -45, top: 24 },
  contourTwo: { width: 280, height: 120, right: -100, top: 65 },
  canopyBack: { position: 'absolute', left: -35, right: -35, bottom: 92, height: 118, borderTopLeftRadius: 120, borderTopRightRadius: 180, transform: [{ rotate: '2deg' }] },
  canopyFront: { position: 'absolute', left: -40, right: 95, bottom: 64, height: 118, borderTopRightRadius: 150, transform: [{ rotate: '-2deg' }] },
  ground: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 88 },
  stream: { position: 'absolute', width: '72%', height: 55, right: -42, top: 3, borderTopLeftRadius: 80, transform: [{ rotate: '-7deg' }] },
  signalPin: { position: 'absolute', width: 29, height: 29, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: palette.paperRaised, backgroundColor: palette.paperRaised, transform: [{ rotate: '-4deg' }], ...shadows.sm },
  signalPinObserved: { backgroundColor: palette.moss, borderColor: palette.paperRaised },
  scanTarget: { position: 'absolute', alignSelf: 'center', top: 82, alignItems: 'center', backgroundColor: alpha(palette.paperRaised, 0.92), paddingHorizontal: 18, paddingVertical: 12, borderWidth: 1, borderColor: alpha(palette.bark, 0.22) },
  scanRing: { width: 57, height: 57, borderRadius: 30, borderWidth: 2, borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center' },
  scanTitle: { color: palette.textStrong, fontSize: 14, fontWeight: '800', marginTop: 7 },
  scanMeta: { color: palette.textMuted, fontSize: 10, marginTop: 2 },
  gain: { position: 'absolute', alignSelf: 'center', top: 45, fontSize: 18, fontWeight: '900', backgroundColor: palette.paperRaised, paddingHorizontal: 8, paddingVertical: 3 },
  sceneCaption: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderTopWidth: 1, borderColor: palette.line, backgroundColor: palette.paperRaised },
  sceneCaptionText: { flex: 1, color: palette.text, fontSize: 11, fontWeight: '600' },
  sceneCounter: { color: palette.mossDeep, fontSize: 10, fontWeight: '800', fontVariant: ['tabular-nums'] },
  resourceStrip: { flexDirection: 'row', alignItems: 'center', marginTop: spacing.md, paddingVertical: spacing.md, borderTopWidth: 1, borderBottomWidth: 1, borderColor: palette.line },
  resourceBlock: { flex: 1, alignItems: 'center' },
  resourceValue: { color: palette.textStrong, fontSize: 17, fontWeight: '800', fontVariant: ['tabular-nums'] },
  resourceLabel: { color: palette.textMuted, fontSize: 9, marginTop: 2 },
  rule: { width: 1, height: 28, backgroundColor: palette.line },
  sectionHeader: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: spacing.md, marginTop: spacing.xl, marginBottom: spacing.sm },
  sectionKicker: { color: palette.barkLight, fontSize: 9, fontWeight: '800', letterSpacing: 1.2 },
  sectionTitle: { color: palette.textStrong, fontFamily: 'Georgia', fontSize: 19, fontWeight: '700', marginTop: 2 },
  textAction: { flexDirection: 'row', alignItems: 'center', gap: 3, paddingVertical: 5 },
  textActionLabel: { fontSize: 11, fontWeight: '800' },
  indicatorGrid: { flexDirection: 'row', flexWrap: 'wrap', borderWidth: 1, borderColor: palette.line, backgroundColor: alpha(palette.paperRaised, 0.72) },
  indicator: { width: '50%', padding: spacing.md, borderWidth: 0.5, borderColor: palette.line },
  indicatorTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  indicatorValue: { color: palette.textStrong, fontSize: 12, fontWeight: '800', fontVariant: ['tabular-nums'] },
  indicatorLabel: { color: palette.textMuted, fontSize: 10, marginTop: 2 },
  indicatorTrack: { height: 4, marginTop: 7, backgroundColor: palette.paperMuted, overflow: 'hidden' },
  indicatorFill: { height: '100%' },
  countNote: { color: palette.textMuted, fontSize: 11, fontWeight: '700' },
  signalList: { gap: spacing.sm, paddingVertical: 2, paddingRight: spacing.lg },
  signalCard: { width: 134, minHeight: 132, padding: spacing.md, borderWidth: 1, borderColor: palette.line, borderTopWidth: 3, borderTopColor: palette.barkLight, backgroundColor: palette.paperRaised },
  signalCardObserved: { borderTopColor: palette.moss, backgroundColor: alpha(palette.moss, 0.05) },
  signalName: { color: palette.textStrong, fontFamily: 'Georgia', fontSize: 13, fontWeight: '700', lineHeight: 17, marginTop: 9 },
  signalHint: { color: palette.textMuted, fontSize: 9, marginTop: 4 },
  observeButton: { marginTop: 'auto', alignSelf: 'flex-start', borderBottomWidth: 2, paddingVertical: 4 },
  observeText: { fontSize: 10, fontWeight: '800' },
  emptyNote: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.lg, borderWidth: 1, borderStyle: 'dashed', borderColor: palette.barkLight, backgroundColor: alpha(palette.paperRaised, 0.55) },
  emptyNoteText: { flex: 1, color: palette.text, fontSize: 12, lineHeight: 18 },
  caseList: { gap: spacing.sm },
  caseCard: { flexDirection: 'row', gap: spacing.md, padding: spacing.md, borderLeftWidth: 4, borderLeftColor: palette.clay, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paperRaised },
  caseCardResolved: { borderLeftColor: palette.moss, backgroundColor: alpha(palette.moss, 0.05) },
  caseIcon: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  caseCopy: { flex: 1 },
  caseTitleRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.sm },
  caseTitle: { flex: 1, color: palette.textStrong, fontSize: 13, fontWeight: '800' },
  caseStatus: { fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  caseProblem: { color: palette.textMuted, fontSize: 11, lineHeight: 16, marginTop: 4 },
  evidenceNote: { flexDirection: 'row', alignItems: 'flex-start', gap: 5, marginTop: 8, paddingTop: 7, borderTopWidth: 1, borderColor: palette.line },
  evidenceText: { flex: 1, color: palette.river, fontSize: 10, lineHeight: 15, fontWeight: '600' },
  resolveButton: { minHeight: 36, marginTop: spacing.sm, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: spacing.md },
  resolveButtonText: { color: palette.inverseText, fontSize: 11, fontWeight: '800' },
  unityNote: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, marginTop: spacing.xl, paddingTop: spacing.md, borderTopWidth: 1, borderStyle: 'dashed', borderColor: palette.line },
  unityNoteText: { flex: 1, color: palette.textMuted, fontSize: 10, lineHeight: 15 },
});
